### PR TITLE
[Frontend] [Relay] make the RepUserType in frontend the same as in relay

### LINKED ISSUE #496: Bug(frontend, relay): claim reputation
**Describe the bug**
voters to claim reputation 
relay:
```sh
Uncaught error TypeError: Cannot read properties of undefined (reading '0')
    at WasmCurve.fromObject (/Users/zhengyawen/Documents/GitHub/social-tw-website/node_modules/ffjavascript/build/main.cjs:4208:38)
    at Object.groth16Verify [as verify] (/Users/zhengyawen/Documents/GitHub/social-tw-website/node_modules/snarkjs/build/main.cjs:1349:32)
    at async /Users/zhengyawen/Documents/GitHub/social-tw-website/packages/relay/src/routes/reportsRoute.ts:31:34
    at async /Users/zhengyawen/Documents/GitHub/social-tw-website/packages/relay/src/services/utils/ErrorHandler.ts:8:13
```
frontend:
```sh
api.ts:373 Uncaught (in promise) Error: Claim reputation failed: undefined
    at relayClaimReputation (api.ts:373:1)
    at async Object.mutationFn (
```
contract
```sh
IdentifierNotRegistered
```

**Expected behavior**
verify reputation proof and claim pos/neg reputation

### PR DESCRIPTION
**Pull request by Xiawpohr**
## Summary

- Change the enum `RepUserType` to 
```
enum RepUserType {
    REPORTER,
    RESPONDENT,
    ADJUDICATOR,
}
```
- Change the enum `RepChangeType` to
```
enum RepChangeType {
    REPORTER_REP = 3,
    RESPONDENT_REP = 5,
    FAILED_REPORTER_REP = 1,
    ADJUDICATOR_REP = 1,
}
``` 

## Linked Issue

close #496 

## Details

The reason why the error occurs is that `RepUserType` is inconsistent between the frontend and the relay so that relayer verify the wrong proof.

### CODE REVIEW

**Review by kittybest — APPROVED** [review]
works for me, thanks!

**Comment by vivianjeng** [comment]
and if I reported myself
截圖 2024-09-12 下午5 03 33

I will get 1 pos rep for 協助檢舉判定
3 pos rep for 檢舉成功
(maybe 1 neg rep for bad post, because my rep balance is 3)

I think maybe author should not report himself
or people can report themselves and gain pos rep

**Comment by kittybest** [comment]
> and if I reported myself 截圖 2024-09-12 下午5 03 33
> 
> I will get 1 pos rep for 協助檢舉判定 3 pos rep for 檢舉成功 (maybe 1 neg rep for bad post, because my rep balance is 3)
> 
> I think maybe author should not report himself or people can report themselves and gain pos rep

encountered same condition wwwwww 
agree with user cannot report themselves, else this condition would happen, kind of weird
so if I only had 2 twitter account, I can never trigger the daily checkin popup box 😂 (since the rep would never be negative)

**Comment by vivianjeng** [comment]
yes I think this PR can be merged first 👍🏻

**Pull request merged**
