### PR TITLE
[Feat] Create signup and login status to upload user interface 

### PR DESCRIPTION
**Pull request by badukwei**
## Summary

Create signup and login status to upload user interface 

## Linked Issue

https://github.com/social-tw/social-tw-website/issues/61

## Details

1. Create signup loading status and login status
2. Upload ui
3. Fix the style for user interface

## Impacted Areas

User.ts
Login.tsx
AppLayout.tsx
PostList.tsx

## Tests

Need to be down.

## Possible Impacts

Test might need to be changed.

## Visual Materials

If your changes have UI effects, consider attaching screenshots or videos to demonstrate them.

## Verification Steps

Follow the sign up process and check the write component is blocked while signing up.

## Todo

Check the test if it needs to be updated

## Checklist

-   [x] All new and existing tests pass
-   [v] I have updated the documentation (if applicable)
-   [v] My changes do not introduce new security vulnerabilities

### CODE REVIEW

**Comment by badukwei** [comment]
@UranusLin and @Xiawpohr , If possible, please check the pr. It might have impact to the test both login and post. I will upload the latest version tommorow.

**Review by Xiawpohr — APPROVED** [review]

**Comment by ryanycw** [comment]
@badukwei Sorry I have few experience in frontend. So if @Xiawpohr approve this, feel free to move forward.

**Comment by ryanycw** [comment]
One minor comment, we are all moving forward to main now, so I would suggest to change the base.

**Comment by badukwei** [comment]
Still need to update, don't merge this branch until finished.

**Pull request merged**
