### PR TITLE
[Fix] epkhelper checking

### LINKED ISSUE #46: UnirepApp.test.ts Refactor
The functions in the test is still not modularized yet and @ryanycw suggested we could use a `util.ts` file to put the functions which can be reused.

Moreover, I deem we should refactor the test file into different section/ files to make the assignments much easier in the future.

### LINKED ISSUE #95: [contract][relay] verify state tree root, caller, epoch
In 2.0.0-beta-4, we move out the `EpochKeyVerifier` from `Unirep.sol` to minimize the core contract size.
But it doesn't check the state tree root (so users might be able to randomly generated a proof without the current Unirep merkle tree), and current epoch.
See [VerifyAndCheckCaller](https://developer.unirep.io/docs/contracts-api/verifiers/epoch-key-verifier-helper#verifyandcheckcaller)

**Suggestion**

*Contract*
https://github.com/social-tw/social-tw-website/blob/6e45b3b3dcd324fddeebc9e64421f5c644cb879d/packages/contracts/contracts/UnirepApp.sol#L88-L92

- Use `verifyAndCheckCaller` to replace `verifyAndCheck`
- Check epoch with [`attesterCurrentEpoch`](https://developer.unirep.io/docs/contracts-api/unirep-sol#attestercurrentepoch)
- Check state tree root with [`attesterStateTreeRootExists`](https://developer.unirep.io/docs/contracts-api/unirep-sol#attesterstatetreerootexists)

*Relay*
This check would prevent submitting tx would be reverted and faster respond to clients.
https://github.com/social-tw/social-tw-website/blob/6e45b3b3dcd324fddeebc9e64421f5c644cb879d/packages/relay/src/routes/post.ts#L72-L82
- Check epoch with [`synchronizer.loadCurrentEpoch()`](https://developer.unirep.io/docs/core-api/synchronizer#loadcurrentepoch)
- Check state tree root with [`synchronizer.stateTreeRootExists`](https://developer.unirep.io/docs/core-api/synchronizer#statetreerootexists)

### PR DESCRIPTION
**Pull request by FoodChain1028**
## Summary

This PR mainly convert `epkHelper.verifyAndCheck` into `epkHelper.verifyAndCheckCaller`, with adding checks with `epoch` and `state tree`. Moreover, this PR also refactored the `Unirep.test.ts`.

## Linked Issue

close #95 close #46

## Details & Impacted Areas

There are main changes in this PR:
### smart contract
1. convert `epkHelper.verifyAndCheck` into `epkHelper.verifyAndCheckCaller`
2. added 2 checks
    - epoch
    - state tree
3. refactor: convert `require()` into `custom error` (to make the consistency) 
4. refactor: `UnirepApp.test.ts` and add new `utils.ts` in contract test

### relay/post.ts
1. added 2 checks
    - epoch
    - state tree

## Todo

Break down the progress of the PR for everyone to see what else you intend to include in this PR.

-   [X] Draft implementation for `function`
-   [X] Unit tests for `function`

## Checklist

-   [X] All new and existing tests pass
-   [X] I have updated the documentation (if applicable)
-   [X] My changes do not introduce new security vulnerabilities
-   [X] Run `yarn lint:fix`

### CODE REVIEW

**Comment by FoodChain1028** [comment]
Hi @vivianjeng, I want to inquire for help in writing a test in checking epoch in smart contract.

I tried to mimic a proof with wrong epoch like this
```
const tree = new IncrementalMerkleTree(STATE_TREE_DEPTH)
const wrongEpoch = 4 * i
const attesterId = unirep.address
const data = randomData()
const leaf = genStateTreeLeaf(
    id.secret,
    attesterId,
    wrongEpoch,
    data
)
tree.insert(leaf)
const { publicSignals, proof } = await genEpochKeyProof({
    id,
    tree,
    leafIndex: 0,
    epoch: wrongEpoch,
    nonce: 0,
    attesterId,
    data,
})
```
Is there any other better method to generate a proof with a different epoch?

**Comment by vivianjeng** [comment]
> Hi @vivianjeng, I want to inquire for help in writing a test in checking epoch in smart contract.
> 
> I tried to mimic a proof with wrong epoch like this
> 
> ```
> const tree = new IncrementalMerkleTree(STATE_TREE_DEPTH)
> const wrongEpoch = 12345
> const attesterId = unirep.address
> const data = randomData()
> const leaf = genStateTreeLeaf(
>     id.secret,
>     attesterId,
>     wrongEpoch,
>     data
> )
> tree.insert(leaf)
> const { publicSignals, proof } = await genEpochKeyProof({
>     id,
>     tree,
>     leafIndex: 0,
>     epoch: wrongEpoch,
>     nonce: 0,
>     attesterId,
>     data,
> })
> ```
> 
> Is there any other better method to generate a proof with a different epoch?

yes you can specify `epoch` in [`userState.genEpochKeyProof`](https://developer.unirep.io/docs/core-api/user-state#genepochkeyproof)
usage
```ts
userState.genEpochKeyProof({epoch: wrongEpoch})
```

**Comment by FoodChain1028** [comment]
> yes you can specify `epoch` in [`userState.genEpochKeyProof`](https://developer.unirep.io/docs/core-api/user-state#genepochkeyproof) usage
> 
> ```ts
> userState.genEpochKeyProof({epoch: wrongEpoch})
> ```

Thank you, but I encountered an error due to transition. It come out with `Error: @unirep/core:UserState user has not transitioned to epoch`.

**Comment by vivianjeng** [comment]
> > yes you can specify `epoch` in [`userState.genEpochKeyProof`](https://developer.unirep.io/docs/core-api/user-state#genepochkeyproof) usage
> > ```ts
> > userState.genEpochKeyProof({epoch: wrongEpoch})
> > ```
> 
> Thank you, but I encountered an error due to transition. It come out with `Error: @unirep/core:UserState user has not transitioned to epoch`.

ah right there is epoch checking in the user state 😅
You might still need to use raw circuit inputs to generate proofs

**Comment by FoodChain1028** [comment]
Hi @vivianjeng, I accomplished the features and tests in both `contract` and `relay`, could you please review the code for me. Thank you so much.

**Review by vivianjeng — APPROVED** [review]
LGTM

**Pull request merged**
