### PR TITLE
[Fix] [Frontend] Generate a negative reputation proof when checking in

### LINKED ISSUE #508: Bug(frontend): fail to claim check in rep
**Describe the bug**

when I try to claim checkin rep
the relay shows

```sh
error InternalError: Positive reputation user
    at Object.<anonymous> (/Users/zhengyawen/Documents/GitHub/vivianjeng/social-tw-website/packages/relay/src/types/InternalError.ts:169:44)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module.m._compile (/Users/zhengyawen/Documents/GitHub/vivianjeng/social-tw-website/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/zhengyawen/Documents/GitHub/vivianjeng/social-tw-website/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/Users/zhengyawen/Documents/GitHub/vivianjeng/social-tw-website/packages/relay/src/types/index.ts:3:1) {
  httpStatusCode: 400
}
```

**To Reproduce**
The author of the reported post wants to claim rep
I think it is caused by
- user should perform UST before claim rep

the `getData` is a little bit confusing because it includes the data that is not transitioned
so if I have `getData = -5`, I cannot generate a valid rep proof to prove `rep<0` since I haven't transitioned
another better function is called [`getProvableData`](https://developer.unirep.io/docs/core-api/classes/UserState#getprovabledata)
to know if the user can generate a `rep<0` proof

### PR DESCRIPTION
**Pull request by Xiawpohr**
## Summary

When user's reputation is negative, generate a negative reputation proof, put this proof in authorization header of check-in API.

## Linked Issue

close #508

### CODE REVIEW

**Comment by kittybest** [comment]
I played in this PR but still only got positive reputation now.

**Review by kittybest — COMMENTED** [review]
The code looks good to me, just me playing in the PR still cannot get negative reputation even I was being reported successfully, so hard to check if the checkin functions.

**Review by kittybest — COMMENTED** [review]
1. I do get both positive and negative reputation
2. I do trigger the daily checkin to pop up if I had negative reputation
3. I clicked on daily checked in, do have +1 to my reputation
4. I cannot do anything when I have negative reputation

however, some issues might relate to this PR, open an issue here: https://github.com/social-tw/social-tw-website/issues/516

if you think it's not related, I would approve this PR and we could deal with the issue in another PR.

**Comment by Xiawpohr** [comment]
@kittybest I think the issue #516 is not in the scope of this PR. We can deal with it in another PR.

**Review by kittybest — APPROVED** [review]
thanks!

**Pull request merged**
