### PR TITLE
Add favicon and change app name

### PR DESCRIPTION
**Pull request by badukwei**
## Summary

Add favicon and change app name

## Linked Issue

close https://github.com/social-tw/social-tw-website/issues/97

## Impacted Areas

packages/frontend/public/index.html
packages/frontend/public/favicon.ico

## Verification Steps

Open with `yarn frontend start` , you can see the result.

### CODE REVIEW

**Comment by kittybest** [comment]
想問一下我們確定要用這個favicon嗎？還是會有我們自己的favicon？

**Comment by badukwei** [comment]
> 想問一下我們確定要用這個favicon嗎？還是會有我們自己的favicon？

我目前是依照 Issue 上的做法去做。
we can use the current logo as favicon. By @vivianjeng.

還是有更好的圖示?
CC @cc03668

**Comment by cc03668** [comment]
我覺得目前使用的 LOGO 做 favicon 沒問題呀～～還是 @kittybest 有其他想法嗎？

**Comment by kittybest** [comment]
> 我覺得目前使用的 LOGO 做 favicon 沒問題呀～～還是 @kittybest 有其他想法嗎？

只是以為會用Social TW那個logo 這個也可以不過就跟我們Unirep Social以及其他Unirep的延伸應用共用logo
沒有不行。

**Comment by badukwei** [comment]
@kittybest @vivianjeng  Merge is still blocked. Please approve this pr. Thanks

**Comment by vivianjeng** [comment]
from my experience, you also need to change the `webpack.config.js`
e.g. https://github.com/Unirep/create-unirep-app/pull/58

**Comment by badukwei** [comment]
> from my experience, you also need to change the `webpack.config.js` e.g. [Unirep/create-unirep-app#58](https://github.com/Unirep/create-unirep-app/pull/58)

Sorry for missing it. It has been added.

**Review by kittybest — APPROVED** [review]

**Review by vivianjeng — APPROVED** [review]

**Pull request merged**
