### PR TITLE
[Fix] #99 update UnirepApp ABI import path

### LINKED ISSUE #99: [relay] use abi from `@unirep/contracts/abi`
https://github.com/social-tw/social-tw-website/blob/6e45b3b3dcd324fddeebc9e64421f5c644cb879d/packages/relay/src/routes/post.ts#L4

**Suggestion**
```ts
 import ABI from '@unirep-app/contracts/abi/UnirepApp.json' 
```
e.g. https://github.com/Unirep/create-unirep-app/pull/59

### PR DESCRIPTION
**Pull request by UranusLin**
Please follow the guidelines in [Contribution.md](https://github.com/social-tw/social-tw-website/blob/main/CONTRIBUTING.md) first, then start to create your pull request here.

## Summary

Updated the import path of `UnirepApp.json` in `post.ts` to point to the correct ABI location.

## Linked Issue

fix #99

## Details

Changed the import path from `@unirep-app/contracts/artifacts/contracts/UnirepApp.sol/UnirepApp.json` to `@unirep-app/contracts/abi/UnirepApp.json` based on the suggestion in the linked issue.

## Impacted Areas
- `social-tw-website/packages/relay/src/routes/post.ts`

## Tests
Existing tests should validate the updated import. No new tests have been added as this is a configuration change.

## Possible Impacts
Any functionality relying on the imported `UnirepApp.json` might be affected if the new location doesn't provide the expected contents. However, since this change is based on a suggestion, it's presumed to be correct.

## Visual Materials
N/A

## Verification Steps
1. Ensure that the new import path in `post.ts` is correct and does not throw any import errors.
2. Confirm that functionalities relying on `UnirepApp.json` are still working as expected after the change.

## Todo
- [x] Update the import path in `post.ts`

## Checklist

-   [x] All new and existing tests pass
-   [ ] I have updated the documentation (if applicable)
-   [x] My changes do not introduce new security vulnerabilities
-   [x] Run `yarn lint:fix`

### CODE REVIEW

**Review by vivianjeng — COMMENTED** [review]
there are several paths needed to be changed
e.g.
https://github.com/social-tw/social-tw-website/blob/fix/issue-99_update-unirep-import-path/packages/relay/src/routes/request.ts

**Comment by UranusLin** [comment]
@vivianjeng how can I get bytecode from `'@unirep-app/contracts/abi/UnirepApp.json'` 

https://github.com/social-tw/social-tw-website/blob/fix/issue-99_update-unirep-import-path/packages/frontend/scripts/deploy-contracts.mjs

**Comment by vivianjeng** [comment]
> @vivianjeng how can I get bytecode from `'@unirep-app/contracts/abi/UnirepApp.json'`
> 
> https://github.com/social-tw/social-tw-website/blob/fix/issue-99_update-unirep-import-path/packages/frontend/scripts/deploy-contracts.mjs

in this case I think using artifacts is fine
or there should be a contract factory `UnirepApp__factory` in `typechain-types` directory
but either the `tsconfig.json` should build the `typechain-types` 
or you add
```js
    typechain: {
        outDir: './typechain',
    },
```
in hardhat.config.ts
to make the output directory be matched 😅

**Review by ryanycw — APPROVED** [review]
I believe the ones that related to the ABI is all solved.

**Review by vivianjeng — APPROVED** [review]

**Pull request merged**
