### PR TITLE
fix: circom installaion

### PR DESCRIPTION
**Pull request by jason-ntu**
## Summary

Update the circom installation commands in readme. We just show people where to find the guide.

## Linked Issue

#69 

## Impacted Areas

README.md

### CODE REVIEW

**Comment by ryanycw** [comment]
I would suggest we learn from the style of Unirep. We don't necessarily have to guide people to install Circom here. We should show people where to find the guide to install Circom since it might be updated over time.
https://github.com/Unirep/Unirep#-requirements

**Comment by jason-ntu** [comment]
> I would suggest we learn from the style of Unirep. We don't necessarily have to guide people to install Circom here. We should show people where to find the guide to install Circom since it might be updated over time. https://github.com/Unirep/Unirep#-requirements

@ryanycw Good idea! I've updated this PR.

**Review by ryanycw — COMMENTED** [review]
Minor issue before we merge this. The Node.js version should be above 18

**Comment by jason-ntu** [comment]
> Minor issue before we merge this. The Node.js version should be above 18

thx for the reminder! I've changed that.

**Review by ryanycw — APPROVED** [review]
LGTM!

**Pull request merged**
