### PR TITLE
fix: fix unirep version (2.1.5-alpha-1)

### PR DESCRIPTION
**Pull request by vivianjeng**
Please follow the guidelines in [Contribution.md](https://github.com/social-tw/social-tw-website/blob/main/CONTRIBUTING.md) first, then start to create your pull request here.

## Summary

State tree leaf id is fixed, there should not be duplicated leaf in indexed db
Fix `InvalidHistoryTreeRoot` and `InvalidStateTreeRoot`

## Linked Issue

If your PR addresses a particular issue, provide its link here.

## Details

Any implementation detail worth pointing out, if any.

## Impacted Areas

List the files or modules that this PR will change.

## Tests

Mention all types of tests (unit, integration, performance, etc.) that you've carried out and if any specific environment or configuration is needed to run them.

## Possible Impacts

Describe any existing features that might be affected by this change, or any potential backward compatibility issues, if any.

## Visual Materials

If your changes have UI effects, consider attaching screenshots or videos to demonstrate them.

## Verification Steps

Provide a step-by-step guide for others to reproduce your results and verify your changes.

## Todo

Break down the progress of the PR for everyone to see what else you intend to include in this PR.

-   [ ] Draft implementation for `function`
-   [ ] Unit tests for `function`

## Checklist

-   [ ] All new and existing tests pass
-   [ ] I have updated the documentation (if applicable)
-   [ ] My changes do not introduce new security vulnerabilities

### CODE REVIEW

**Review by Xiawpohr — APPROVED** [review]
I test successfully these features including post, comment, vote, report, adjudicate, and check-in.

**Comment by kittybest** [comment]
also another issue (should open another issue ticket)
image
the thumb up amount should be updated

**Comment by kittybest** [comment]
& this issue again:
image
I should have 1 reputation, but only got 0

**Comment by kittybest** [comment]
image
image

another issue: if the user is a negative user, then the adjudicate popup shouldn't be shown on his/her page.

**Comment by Xiawpohr** [comment]
> & this issue again: image I should have 1 reputation, but only got 0

I need to the reproducible steps to confirm this issue in my local environment.

**Pull request merged**
